### PR TITLE
typography & spacing changes

### PR DESCRIPTION
**Pull request by mkhandekar**
#### This pull request includes adjustments including:
- smaller hero text
- added spacing below hero text
- smaller & lighter footer text
- updated favicon

**Help needed:**
Generally this is the spacing I'm looking for between 1) box border & top of logo, and 2) bottom box border and top of "we're currently upgrading". When I resize the browser window, this spacing reduces, and I don't quite know how to retain similar (or at least proportional) spacing on smaller screen sizes. Any ideas @adelevie & @juliaelman?

**Target:**
myusa_comingsoon_v4c

**Regular / desktop:**
desktop

**Smaller sizes / responsive**
responsive

### CODE REVIEW

**Comment by juliasolorzano** [comment]
@mkhandekar thanks for the pull request! :+1: 

Just to confirm, the changes made in this pull request are to adjust the sizing to spec on larger screen sizes - correct?

**Comment by mkhandekar** [comment]
@juliaelman That's right, adjustments were made for larger screen sizes.

**Comment by juliasolorzano** [comment]
@mkhandekar great! I just pushed up some fixes for your review and hope that fixes the spacing issues on smaller screen sizes.

@adelevie once approved, I can merge these changes into the `starter` branch and I think we should be good to go?

**Comment by adelevie** [comment]
Yep, @juliaelman. Last piece will be the email form. I am planning to add this myself later today, unless this is something either you or @mkhandekar wants to add.

**Comment by juliasolorzano** [comment]
@adelevie ah, ok! I was wondering what we were doing about that, based on the original design. Happy to add it to this PR shortly.

**Comment by juliasolorzano** [comment]
@adelevie @mkhandekar added the input field + submit button + their responsive behavior! :tada: 

#2 looks like it syncs up with this work.

**Comment by adelevie** [comment]
This all looks fantastic. Excellent work @mkhandekar and @juliaelman!

**Comment by adelevie** [comment]
screen shot 2015-04-09 at 1 29 05 pm

**Comment by adelevie** [comment]
screen shot 2015-04-09 at 1 37 01 pm

**Comment by adelevie** [comment]
Latest commit fixes the previous two accessibility issues.

**Pull request merged**
