### PR TITLE
Very ROUGH cut of copy and HTML starter

### PR DESCRIPTION
**Pull request by adelevie**

### CODE REVIEW

**Comment by adelevie** [comment]
Latest commit looks like:

screen shot 2015-04-06 at 3 31 45 pm

The target design is:

screen shot 2015-04-06 at 3 32 34 pm

**Comment by adelevie** [comment]
TODOs:
- [x] Use smaller logo
- [x] Shrink hero body text a tad
- [x] Add a little bit of line spacing to hero text
- [x] Put bottom text into the same span, add a bit of line spacing
- [x] Make "want more info..." bold
- [x] Add placeholder for email collecter
- [x] Shrink footer text
- [x] Make footer text grey
- [x] Add tiny flag to the left of footer text

**Comment by adelevie** [comment]
@juliaelman, the latest commit makes the site somewhat responsive. I used [localtunnel](https://localtunnel.me/) to test on my phone which has 1920x1080 resolution. It looks fine on this, imo, but I'm wondering if/how we can test on some smaller screens.

The final piece that's needed is the email collector.

**Comment by juliasolorzano** [comment]
@adelevie nice work! I tested on [Chrome's phone emulator](https://developer.chrome.com/devtools/docs/device-mode) for several devices first and everything looked okay there. Then, I tested on Firefox 37.0.1 at the smallest screen width and it looks like there is a font + logo sizing issue, see screenshot below.

screen shot 2015-04-08 at 8 55 37 am

**Comment by adelevie** [comment]
Great catch, @juliaelman! Fixing ...

**Comment by adelevie** [comment]
:shipit: :ship: :dragon_face:

**Pull request merged**
